### PR TITLE
Stop running Live365 tasks

### PR DESCRIPTION
**Pull request by lund5000**
# What kind of change does this PR introduce? 
Removes the `Live365Listener` when a track is added to the playlist

# What is the current behavior? 
CHIRP no longer uses Live365. The tasks attempting to send track information to Live365 are repeatedly generating a 500 error when run. Since they don't seem to be respecting the limits defined in `queue.yaml` there are close to 15,000 of these tasks running and failing every day.

# What is the new behavior?
Track information is still sent to chirpradio.org ("live site") and increments a PlayCount entity for that track, but should no longer generate the failing Live365 tasks.

# What else?
I can't actually get this particular app to run and find the Google App Engine SDK, so this is totally untested. I broke this into two commits: a one line commit that removes the listener but leaves all the related code in the repo, and a larger commit that removes all the related code. It all *seems* right, but I could be missing something.

### CODE REVIEW

**Comment by kumar303** [comment]
Also, if you figure out any of that stuff ^ please update the docs 😄

**Comment by kumar303** [comment]
It looks like there are [Docker containers for the App Engine runtime](https://github.com/GoogleCloudPlatform/python-runtime). This might let you run the app locally but, I dunno, the local App Engine SDK used to be really different from the actual runtime.

**Comment by kumar303** [comment]
@lund5000 were you able to test this locally? If you have anything to add to / edit in the docs, please do.

**Comment by lund5000** [comment]
@kumar303 I was not able to test it locally since I couldn't get the app to find and load the App Engine SDK I have installed. We instead deployed the code without promoting the new version, tested it on the version-specific URL, then gradually sent more traffic to the new version while monitoring errors.

**Comment by kumar303** [comment]
@lund5000 awesome. It would be great to mention that testing process [here](https://chirpradio.readthedocs.io/en/latest/topics/deployment.html) so that we remember how to do it next time. That file is at https://github.com/chirpradio/chirpradio/blob/master/docs/source/topics/deployment.rst

**Pull request merged**
